### ISSUE TITLE
Create a simple Dune dashboard for AI agents

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#125]
The idea for this Dune dashboard is to have a public display of the performance of our agents and the overall metrics related to their operation (see metrics for more details). 

Main metrics
    - transactions of each agent
    - percentage of correct bets / all bets
    - how much money do they control in aggregate
    - daily trading volume

**Comment by kongzii** [comment]
Closing as Hugo is actively working on this: https://dune.com/hdser/omen-ai-agents
