### ISSUE TITLE
Define criteria for bet sizes

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#157]
Having worked a bit more in the PMA (https://github.com/gnosis/prediction-market-agent) repo, I believe we should think about having some infrastructure for the agent being able to determine the size of each bet. Currently this is the (standard) implementation for this:

```
def calculate_bet_amount(self, answer: bool, market: AgentMarket) -> BetAmount:
    """
    Calculate the bet amount. By default, it returns the minimum bet amount.
    """
    return market.get_tiny_bet_amount()
```

One option that comes to mind is let the agent determine the amount, based on a number of factors, e.g. xDAI balance, confidence on prediction, time left for market to close, etc. Those are all parameters we can already provide the agent.

**Comment by kongzii** [comment]
Moved to PMA and will close this one: https://github.com/gnosis/prediction-market-agent/issues/56
