### ISSUE TITLE
Enable agents to base their betting strategy on their predicted `p_yes`

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#161]
Currently `DeployableAgent.calculate_bet_amount` only takes in a boolean answer, and the market. It should take in a prediction that optionally includes the predicted `p_yes`.

This would require `DeployableAgent.answer_binary_market` returning an answer that optionally contains the `p_yes` too.

See https://github.com/gnosis/prediction-market-agent-tooling/blob/9633cdacd0277f96088d54d7703f285ce23c055d/prediction_market_agent_tooling/deploy/agent.py#L196

**Comment by gabrielfior** [comment]
I would also add that the `bet_size`, besides being dynamic, should also take into consideration the current belief of the market and compare that against the `p_yes` of the model. So if current belief is `Yes = 60` and model says `p_yes=90`, let's bet on yes, and so on.
Here some more info on this -> https://docs.gnosis.io/conditionaltokens/docs/introduction3/

**Comment by kongzii** [comment]
Linking this issue as it seems to be related https://github.com/gnosis/prediction-market-agent-tooling/issues/104

**Comment by kongzii** [comment]
`calculate_bet_amount` now accepts both ` answer: Answer` and `market: AgentMarket`
