### ISSUE TITLE
Fix OmenMarket.p_yes calculation

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#181]
https://github.com/gnosis/prediction-market-agent-tooling/blob/main/prediction_market_agent_tooling/markets/omen/data_models.py#L231

We calculate `p_yes` based on `outcomeTokenAmounts`. For markets that have had their liquidity remove (or closed markets in general? t.b.c) `outcomeTokenAmounts` == [0, 0], and therefore this always returns 0.5.

Instead it should get the token amount at the time of the last trade, or something like that. Maybe there's a better way altogether than looking at `outcomeTokenAmounts`. Needs investigating.

**Comment by kongzii** [comment]
This should be done by https://github.com/gnosis/prediction-market-agent-tooling/pull/201
