### ISSUE TITLE
Make Brier score formula consistent with Dune dashboard

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#202]
Our dune dashboard (https://dune.com/queries/3633110/6119768) uses the 'original' multi-class definition of Brier score (https://en.wikipedia.org/wiki/Brier_score#Original_definition_by_Brier). This is effectively 2x the score we calculate in our monitoring and benchmarking code. Fix to make them consistent.

**Comment by kongzii** [comment]
Will be changed by https://github.com/gnosis/prediction-market-agent-tooling/pull/221
