### ISSUE TITLE
Rework tests marked as @pytest.skip when local chain is available for tests

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#206]
On this issue (#99 ) , we will implement a local chain ([anvil based](https://book.getfoundry.sh/reference/anvil/)) that is started for testing (forking a local state from Gnosis), then tests are executed, then the chain is killed.

On that issue, some of the skipped tests were executed and the decorator was removed since they were executed successfully.
Other tests (marked with `@pytest.mark.skip(reason=DEFAULT_REASON)`) need reworking (see comments on each test). This rework is normally associated to usage of subgraphs or other tools, that don't get updated on the local chain - instead, directly reading from the local chain is the way to assert if state has been changed.

**Comment by gabrielfior** [comment]
Depends on #99

**Comment by evangriffiths** [comment]
Some tests re-worked. Can close, and create new tickets for specific remaining tests if needed
