### ISSUE TITLE
Fix `claim_bonds_on_realitio_question` function if len(answers) > 1

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#318]
Currently, `claim_bonds_on_realitio_question` works only on questions with a single answer, for more of them, it will break.

Because we expect to have multiple answers in the near future, we need to fix this.

After we fix it here, we can also push a PR into Olas repository.

**Comment by evangriffiths** [comment]
Fixed by https://github.com/gnosis/prediction-market-agent-tooling/pull/368
