### ISSUE TITLE
Improve resolution accuracy on Omen

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#319]
We aim to improve resolution accuracy on Omen, there are multiple ways to achieve this:

1. Use people thanks to high-enough bonds on Reality.eth (Kleros will take care of getting people there once the bonds are reasonable for them)
2. Increase LLM-resolver accuracy

A combination of both of them is ideal, for increasing the bonds, there are again multiple ways:

1. Olas could increase the bond from 0.1 to 10 xDai in market-creator.
2. We could create an agent that will copy-paste the market-creator's answers in all markets, but with increased bond to $10.
3. We could use OFV and post answers only on questions where market-creator and OFV disagree
4. We could use OFV and post all its answers, no matter if it agrees with market-creator or not

We don't like (3) and (4) because we already have OFV in pull request to mech repository, and these go against contributing to Olas system. 

For increasing the LLM resolution accuracy:

1. Merge OFV to Olas
2. Or instead, do (3) or (4) from the previous points
3. After OFV is used in one way or another, we could identify its weak points and create yet another LLM resolver that will challenge the answers and make it more and more interesting for people to jump in, because of increased bonds

**Comment by kongzii** [comment]
We agreed @evangriffiths will look at `1. Olas could increase the bond from 0.1 to 10 xDai in market-creator.` by asking them and maybe opening PR as well, as that's the easiest and quickest solution right now.

**Comment by evangriffiths** [comment]
> We agreed @evangriffiths will look at `1. Olas could increase the bond from 0.1 to 10 xDai in market-creator.` by asking them and maybe opening PR as well, as that's the easiest and quickest solution right now.

PR here https://github.com/valory-xyz/market-creator/pull/111

**Comment by kongzii** [comment]
I think this can be closed in favor of https://github.com/gnosis/prediction-market-agent/issues/457. It's issue for option (4) as OFV in Olas is still not used.
