### ISSUE TITLE
Add support for other collateral tokens than wxDai in the remaining functions.

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#321]
https://github.com/gnosis/prediction-market-agent-tooling/pull/320 added this support in market creation, but if we want to use such markets, we need to add it also in:

- omen_buy_outcome_tx
- omen_sell_outcome_tx
- omen_fund_market_tx
- test_place_bet_with_autodeposit

After these are done and tested, we can remove this TODO:

https://github.com/gnosis/prediction-market-agent-tooling/blob/f71bddfcebae6fc95f1e971d6e7b49bd9fbf67cd/prediction_market_agent_tooling/markets/omen/omen_subgraph_handler.py#L343

And freely use markets with any collateral token.

**Comment by evangriffiths** [comment]
@kongzii fixed!
