### ISSUE TITLE
Add Circles as supported collateral token

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#322]
https://github.com/gnosis/prediction-market-agent-tooling/pull/320 started movement for arbitrary collateral tokens on Omen and should have finished it https://github.com/gnosis/prediction-market-agent-tooling/issues/321.

Now we can add Circles to the list of supported tokens. Maybe it will be easy peasy, and all will work by default, but perhaps it will need some changes, as Circles is a unique thing.

**Comment by gabrielfior** [comment]
If we can have a standard way of wrapping Circles tokens, then the implementation becomes trivial (i.e. Circles as an ERC20 token). I can check with the Circles team.

**Comment by gabrielfior** [comment]
This ticket was splitted into 3 (#327 , #328 , #329 ), hence closing this.
