### ISSUE TITLE
Refactor DeployableTraderAgent to 1. predict a probability for a market then 2. place a bet based on its `BettingStrategy`

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#338]
May need a refactor of `DeployableTraderAgent.process_bets` (see https://github.com/gnosis/prediction-market-agent-tooling/blob/69ec60e8206ac64bbabc8707d8b62d251d699e54/prediction_market_agent_tooling/deploy/agent.py#L281)

Currently it does:
```
result = self.answer_binary_market(market)
amount = self.calculate_bet_amount(result, market)
market.place_bet(amount=amount, outcome=result.decision)
```

The abstraction is a bit off here if we want to use `get_kelly_bet` [here](https://github.com/gnosis/prediction-market-agent-tooling/blob/69ec60e8206ac64bbabc8707d8b62d251d699e54/prediction_market_agent_tooling/tools/betting_strategies/kelly_criterion.py#L21), as we want to calculate the direction and amount together, so it would look like:

```
prediction = self.predict_binary_market(market)
bet = self.get_bet_from_prediction(market, prediction)
market.place_bet(amount=bet.amount, outcome=bet.direction)
```

**Comment by evangriffiths** [comment]
Re-opening, as https://github.com/gnosis/prediction-market-agent-tooling/pull/352 didn't actually change the default

**Comment by gabrielfior** [comment]
> Re-opening, as #352 didn't actually change the default

@evangriffiths do you mind closing this ticket in favor of https://github.com/gnosis/prediction-market-agent-tooling/issues/365?
