### ISSUE TITLE
Make test `test_local_deployment` use chain fork instead of the real chain

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#353]
The test `test_local_deployment` uses Gnosis Mainnet in its attempt to run the agent - basically it triggers `agent.run` (without placing bets), but it does try to redeem positions.
This is interfering with the operation of the deployed agent - see errors e.g. here
https://github.com/gnosis/prediction-market-agent-tooling/actions/runs/10479070131/job/29023879784#step:7:262
and here
https://github.com/gnosis/prediction-market-agent-tooling/actions/runs/10478961453/job/29023515375#step:7:223

Note that the position_id as well as the index on the logs increases, thus if you re-try long enough the tests will eventually pass.

The test would be more robust if executed on a local fork (using the existing pytest fixture `local_web3`), since all positions exist there as well.

**Comment by kongzii** [comment]
Makes sense, implemented here https://github.com/gnosis/prediction-market-agent-tooling/pull/523
