### ISSUE TITLE
Universal place to store information about the bet

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#363]
We need to store somewhere:

- predicted probability 
- reasoning about the prediction
- ? maybe something else

Omen contracts are public, and Presagio is as well, so the solution should be usable by everyone, such that anyone's agent can contribute it.

@evangriffiths says let's host a public Postgres

@kongzii Complains that Postgres is too web2ish! Let's create a new contract for it.

@gabrielfior Says some fancy web3storage solution exists.

Goals:

- Presagio can show it as bet's details
- We can use it on Dune to track accuracy and other fancy metrics based on probability

**Comment by kongzii** [comment]
>? maybe something else

There could be also `is_agent: bool` flag that Presagio could use to flag the bets as AI on the UI. Right now, they are querying it from Dune.

**Comment by gabrielfior** [comment]
I'm thinking about a way to use IPFS to solve this - maybe leveraging this project (https://storacha.network/).
We would have a central file containing a dictionary (market_id -> prediction_str_IPFS_hash (and other metadata)), so we could fetch the information on a series of IPFS addresses.
The unsolved question is: how do we add more market_ids to the initial file and keep it addressable, since changing the file contents will change its CID?

**Comment by kongzii** [comment]
For IPFS we have already Pinata from devops.

But I’m afraid that we would have the same unsolvable problems as with image mapping (which ended up being a contract)

**Comment by kongzii** [comment]
Note: Here it would make sense to me if the solution is upgradable in a backward-compatible way. If we want to add some new fields or something in the future.

**Comment by berteotti** [comment]
On Presagio side it would be good to query this info by agent_id and market_id. So somewhere on the data or some kind of index with this info would be appreciated. On our side we see this data has relevant:

- Reasoning about the prediction (this could look like a comment about the decision)
- Predicted probability
- Model used (already present in mechs data)
- Data sources for the reasoning (news, articles, etc.), if possible

> There could be also `is_agent: bool` flag that Presagio could use to flag the bets as AI on the UI. Right now, they are querying it from Dune.

This means that the "database" will have agent and non-agent information?

**Comment by evangriffiths** [comment]
> Note: Here it would make sense to me if the solution is upgradable in a backward-compatible way. If we want to add some new fields or something in the future.

This seems harder if using a smart contract (immutable once deployed, no version control), but apparently not impossible (using a proxy contract -> implementation contract pattern). Might want to consult someone with more solidity expertise than me about this thoughhhh 😅 

> There could be also is_agent: bool flag that Presagio could use to flag the bets as AI on the UI. Right now, they are querying it from Dune.

Aren't all predictions by definition from agents if they are stored in this db?

**Comment by kongzii** [comment]
> Might want to consult someone with more solidity expertise than me about this thoughhhh 😅

@gabrielfior To the rescue! 🦸 

> Aren't all predictions by definition from agents if they are stored in this db?

Well yeah, but if it's public, then theoretically anyone can contribute there, including humans.

**Comment by gabrielfior** [comment]
I think the simplest way to go here would be to have
a. Modifications to the agent that make sure `p_yes`, `reasoning`, etc are stored - my understanding is this is already done to some extent, e.g. Langfuse or even DB.
b. Cron job executes a script that fetches the information above and pushes to Dune (https://docs.dune.com/api-reference/tables/endpoint/insert).
c. Third-parties (like Presagio) can consume this data either from [Dune](https://docs.dune.com/api-reference/queries/endpoint/read) or from the gnosis-labs API (if through the latter, additional endpoints needed but probably still not too much work)

Apart from the option above, I see following options:
- Use IPFS/IPNS for data versioning (an interesting wrapper on top of this is web3.storage or Storacha - https://web3.storage/docs/how-to/w3name/) - in talks with them
- Store things in a smart contract on chain (similar to the Image Thumbnail contract) - this could be integrated with the Graph hence easy querying

> Note: Here it would make sense to me if the solution is upgradable in a backward-compatible way. If we want to add some new fields or something in the future.
I didn't follow why upgrade would be required here - if indeed it is, then as @evangriffiths said, [ProxyPattern](https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies) is the way to go.

**Comment by kongzii** [comment]
> Use IPFS/IPNS for data versioning (an interesting wrapper on top of this is web3.storage or Storacha - https://web3.storage/docs/how-to/w3name/) - in talks with them

How would you deal with concurrency? And what would be the benefit of using them vs. just storing it in contract as with image mapping?

**Comment by gabrielfior** [comment]
Another idea: I suggest we also explore the following as alternative to smart contracts
-> orbisDB (https://github.com/OrbisWeb3/orbisdb)

Pros
- Looks and feels like a Postgres DB (but decentralized, powered by Ceramic - think of it as Kafka (event-powered) but also on-chain
- GraphQL-server support for serving data

Cons
- Infra effort required (running Ceramic node)
- Only Typescript client (we would need either a. Python client from scratch or b. a backend written in TS that redirects requests to Orbit (kind of a proxy)

**Comment by gabrielfior** [comment]
Pasting here the discussion between @gabrielfior and @kongzii :
-> Smart contract work seems the best choice, given that gas fees are not huge (for thumbnail, gas fee is < 0.001 xDAI) and we can leverage subgraphs for data querying. Due to the blockchain being present, it also offers a native solution to concurrency.
-> Idea is to have a mapping (similar to the thumbnail case) that looks like
```
// trades is not the best name but no better name occurs to me
mapping(address => [bytes32]) private trades; // new predictions appended to market ID (ipfs hash of the prediction)
```
The IPFS object should look like this and will be shared among the 2 use cases we envision for this, trading activities (https://github.com/gnosis/prediction-market-agent-tooling/issues/365) and task queue (https://github.com/gnosis/prediction-market-agent/issues/462) :
```
// 1. Trading use case
data: {"probability": 0.9, "reason": "I know everything", ...},
data_types: [{"key": probability, python_type: "float"},{"key": reason, type: str}, ...]

// 2. Task queue use case
// Not 
data: {"task_description": "Send me a research report to [a@b.com](mailto:a@b.com) about topic X.",
"result": "Here's the report - bla bla bla"},
data_types: [{"key": task_description, python_type: "str"},{"key": result, type: str}, ...]
```

With the `types` above, we are able to leverage Pydantic for model validation.

**Comment by gabrielfior** [comment]
Completed https://github.com/gnosis/labs-contracts/pull/7
