### ISSUE TITLE
Make Kelly default betting strategy

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#365]
-> Do this once we are able to query/store agent's probabilities for tracking acuracy (which will be affected once Kelly's decides bet direction) - i.e. start after https://github.com/gnosis/prediction-market-agent-tooling/issues/363 is merged

**Comment by evangriffiths** [comment]
Fixed by https://github.com/gnosis/prediction-market-agent/pull/494
