### ISSUE TITLE
`BettingStrategy.calculate_bet_amount_and_direction` should be able to take `wallet_balance` arg

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#377]
Atm all betting strategies define max bet size at initialization time. However, this means an agent can't increase its bet size as its balance increases. This should be possible so % returns don't diminish for a profitable agent.

**Comment by evangriffiths** [comment]
@kongzii @gabrielfior and I all say `max_bet=wallet_balance * 0.9` is a good idea

**Comment by kongzii** [comment]
Blocked until we solve https://github.com/gnosis/prediction-market-agent-tooling/pull/419#issuecomment-2363142241 , for now let's go with fixed max bet amount of 2?

**Comment by evangriffiths** [comment]
Actually, it's okay to do this for KnownOutcomeAgent (see #419)

**Comment by evangriffiths** [comment]
from today's sync: For KnownOutcomeAgent, use KellyBettingStrategy with dynamic max_bet_amount, `max_bet_amount = min(25, wallet_balance * 0.5)`, so it doesn't run out of funds quickly
