### ISSUE TITLE
Add a getter method that creates `DeployedAgent` from queries to GCP

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#38]
Use GCP cli/client to get deployed agents and parses them to a list of `DeployedAgent` instances that can be used to populate the monitoring app.

A prerequisite is that the GCP cloud functions themselves have the correct metadata/tags:
- Descriptive name
- Start time
- wallet address/manifold account
- more?

**Comment by kongzii** [comment]
This is handy for https://github.com/gnosis/prediction-market-agent-tooling/issues/28,  so assigned to myself

**Comment by kongzii** [comment]
Done in https://github.com/gnosis/prediction-market-agent-tooling/pull/54
