### ISSUE TITLE
Simulate payout of prediction-prophet-gpt4 if we were using Kelly

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#381]
- We have the positions the agent had when market was resolved (Dune and/or subgraph)
- We can call the `get_kelly_bet` and get a bet_amount we would use (let's make this variable, e.g. `max_bet_amount = [1,2,5,10]`
- We can then calculate the payout per position, average this out per month, etc and compare with our current payouts

**Comment by kongzii** [comment]
Don't we also need agent’s predicted probability to compute Kelly? If agent bought position when market was at 60%, it doesn't mean agents probability wasn't 51% or 99%.

You should be able to query it from Langfuse relatively easily.

**Comment by evangriffiths** [comment]
See https://github.com/gnosis/prediction-market-agent-tooling/pull/419 for simulation results. Looks like switching to kelly is a good idea!
