### ISSUE TITLE
Create subgraph for mapping marketId -> list[ipfsHashes]

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#403]
-> Subgraph for #402

**Comment by gabrielfior** [comment]
I would suggest using [envio](https://envio.dev/explorer) for creating a subgraph for this and hosting using our cloud provider. Locally it took me 3 mins to have a local indexer running and serving GraphQL requests.
FYI Metri team is using Envio.

**Comment by kongzii** [comment]
> hosting using our cloud provider. 

I thought you agreed that having as little of production APIs as possible on our side is preferable. Plus all other subgraphs are on thegraph (omen, reality, conditional tokens)

**Comment by gabrielfior** [comment]
Completed https://github.com/gnosis/labs-contracts/pull/11
