### ISSUE TITLE
Increase `bet_on_n_markets_per_run` to `MAX_AVAILABLE_MARKETS` (20) 

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#410]
This increases number of markets we place bets on - should increase our payout given that our accuracy is high for markets closing soon.

**Comment by kongzii** [comment]
Note: Increase only for agents that won't cost a fortune. I.e. for sure not for the o1-preview agent.

**Comment by kongzii** [comment]
https://github.com/gnosis/prediction-market-agent/pull/475
