### ISSUE TITLE
Kleros Arbitrator is outdated and creates disputes with no possibility for appeal

### ISSUE THREAD

**Issue by greenlucid** [gnosis/prediction-market-agent-tooling#444]
The current Kleros Contract, https://github.com/gnosis/prediction-market-agent-tooling/blob/247e7b25b255ca2a614286b4fe1b1ce8613312af/prediction_market_agent_tooling/markets/omen/omen_contracts.py#L489

`0xe40DD83a262da3f56976038F1554Fe541Fa75ecd`, which was probably found here: https://docs.kleros.io/developer/deployment-addresses

is in Gnosis Chain, links to this proxy in Mainnet:

[0x79d0464Ec27F67663DADf761432fC8DD0AeA3D49](https://etherscan.io/address/0x79d0464Ec27F67663DADf761432fC8DD0AeA3D49)

it has NO appeals. This is a problem if a market escalates.

Historically, this was the one used: [0xd47f72a2d1d0e91b0ec5e5f5d02b2dc26d00a14d](https://etherscan.io/address/0xd47f72a2d1d0e91b0ec5e5f5d02b2dc26d00a14d) but I don't know why it's not the one in there. I assume due to some MetaEvidence bugs that forced it to be updated.

---

Anyhow, no appeals is a problem. If you check [0x79d0464Ec27F67663DADf761432fC8DD0AeA3D49](https://etherscan.io/address/0x79d0464Ec27F67663DADf761432fC8DD0AeA3D49) and read the `arbitratorExtraData`, after some digging you'll find how it will intend to create a dispute with 511 jurors, and provides no interface whatsoever to appeal. Even if it did, it cannot be appealed anyway since that's the max amount of jurors that can be summoned.

For context, which is not shown anywhere and might be important for the prompting in some of the agents, this is the policy that would currently be put in place if a question ever escalated: https://cdn.kleros.link/ipfs/QmZM12kkguXFk2C94ykrKpambt4iUVKsVsxGxDEdLS68ws/omen-rules.pdf

Now, if you want disputes with appeals (and I'm pretty sure you do, consult @clesaege on this), you need to setup a different proxy, it's also found on Kleros Deployments.

This will be the Mainnet Proxy: [0x2F0895732bfacdCF2fdB19962fE609D0dA695F21](https://etherscan.io/address/0x2F0895732bfacdCF2fdB19962fE609D0dA695F21)

And, this is the one it connects to, which is the arbitrator you should setup if you want disputes: [0x29f39de98d750eb77b5fafb31b2837f079fce222](https://gnosisscan.io/address/0x29f39de98d750eb77b5fafb31b2837f079fce222)

This will be the policy in use: https://ipfs.kleros.io/ipfs/QmaUr6hnSVxYD899xdcn2GUVtXVjXoSXKZbce3zFtGWw4H/Question_Resolution_Policy.pdf, if you go through this make sure it doesn't break assumptions in agents.

**Comment by kongzii** [comment]
Hey, thanks a lot for the detailed explanation! And even more for the PR right away for it. I agree with your points, but originally I took the contract's address from the old [omen.eth source codes](https://github.com/protofire/omen-exchange/blob/f35d30614e92baa50d0787cd8203668fdb59ee3b/app/src/util/networks.ts#L660C28-L660C69), so feels like we should discuss this more internally before merging the PR.

**Comment by greenlucid** [comment]
Any channels, discord, tg etc that are open so that I can join these discussions and learn more? Or are those internal discussions private? @kongzii

**Comment by kongzii** [comment]
I only brought it up on our sync call, otherwise this issue or Gnosis' Discord gnosis-ai channel are good places to discuss.

**Comment by kongzii** [comment]
I believe this issue can be closed now, Green feel free to re-open if I missed something. To wrap it up:

[In PMAT (and therefore PMA agents), we default to Kleros with 31 jurors on Eth](https://github.com/gnosis/prediction-market-agent-tooling/blob/05535b1193a82ac6caef875eef0b201a69bad4a4/prediction_market_agent_tooling/markets/omen/omen_contracts.py#L541). 

However, it's configurable. If someone wants to contribute Kleros contract with a 0.05 ETH fee, it's welcome, but not required atm.

Plus [I also opened PR on Olas repository](https://github.com/valory-xyz/market-creator/pull/120). 

Currently, Olas is creating more markets than Gnosis AI, so until that PR is merged and deployed, we will still see high arbitration fees.
