### ISSUE TITLE
Evaluate probability estimation of agents

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#454]
The following experiment for each agent:

1. Bucketize all bets by probability, e.g. 0-10% bucket, 10-20% bucket , etc.
2. In each bucket, get the real probability of markets in them: `len(markets resolved as yes in this bucket) / len(all markets in this bucket)` 
3. Optionally, consider only bets with confidence >= <some threshold>

The real probability should be within the bucket. We can use that to either calculate "probability accuracy" or MSE between the bucket and real probability.

It would be nice to have it on Dune, but it should be fast to implement in this script so probably best to get the results right away: https://github.com/gnosis/prediction-market-agent-tooling/blob/main/examples/monitor/match_bets_with_langfuse_traces.py

**Comment by gabrielfior** [comment]
Possibly a duplicate of https://github.com/gnosis/prediction-market-agent/issues/477

**Comment by kongzii** [comment]
> Possibly a duplicate of https://github.com/gnosis/prediction-market-agent/issues/477

Right! I was looking for "probability" in issue titles. Will close this.
