### ISSUE TITLE
Don't force IPFS hash upload in DeployableTraderAgent

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#468]
Currently, the agent tries to upload IPFS no questions asked: https://github.com/gnosis/prediction-market-agent-tooling/blob/735edab65333a22f3de68f8ccf0a2e992e28b809/prediction_market_agent_tooling/deploy/agent.py#L525

I'd say this should be either behind a flag or it should happen only if PINATA_API_KEY is present in the APIKeys. 

I wouldn't expect people to create Pinata accounts because of us or to pay for them if they are already using the free tier for something else.

**Comment by gabrielfior** [comment]
> I'd say this should be either behind a flag or it should happen only if PINATA_API_KEY is present in the APIKeys.

Agree with putting this behind a flag (False by default). Implementing this.
