### ISSUE TITLE
Integrate Kleros' Seer platform into PMAT

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#484]
https://seer-3.gitbook.io/seer-documentation/developers/contracts
https://seer.pm/

Functionalities (similar to Omen)
-> CreateMarket (NOT conditional) --> this also involves creating pool on Swapr
-> Buy tokens - interacting with Swapr pool (but can be expanded to include Cowswap trades)
-> Sell tokens - same as above
-> Redeem winnings - different contract than Omen (not FixedProductMarketMaker)

**Comment by greenlucid** [comment]
I would enjoy working on this to learn the ropes on the repo, is that possible or is this a priority?

**Comment by gabrielfior** [comment]
> I would enjoy working on this to learn the ropes on the repo, is that possible or is this a priority?

@greenlucid feel free to pick this up! Happy to provide support if needed.

**Comment by gabrielfior** [comment]
This was split into [multiple, smaller tasks](https://github.com/gnosis/prediction-market-agent-tooling/issues?q=is%3Aissue+is%3Aopen+label%3Aseer) for greater visibility - @greenlucid feel free to pick one up (a good start in my opinion would be https://github.com/gnosis/prediction-market-agent-tooling/issues/496) and let us know if you need input/clarifications. Thanks for contributing!

**Comment by kongzii** [comment]
This is also needed if we want to support Seer: https://github.com/gnosis/prediction-market-agent-tooling/issues/510

@greenlucid If you would be implementing something for Seer that's using market outcomes, I think it's easiest to consider only `Yes, No` markets and others will be supported later on by #510
