### ISSUE TITLE
Finish withdrawing of funds in https://github.com/gnosis/prediction-market-agent-tooling/pull/79

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#80]
https://github.com/gnosis/prediction-market-agent-tooling/pull/79

**Comment by gabrielfior** [comment]
@kongzii I believe this functionality has been implemented on https://github.com/gnosis/prediction-market-agent-tooling/pull/98 - if so, I would suggest to close this

**Comment by kongzii** [comment]
@gabrielfior Doesn't look like it was:

![Screenshot by Dropbox Capture](https://github.com/gnosis/prediction-market-agent-tooling/assets/15619339/ab3e9fb5-b670-4aac-9b2e-ad14661bb2af)

Did you test that what https://github.com/gnosis/prediction-market-agent-tooling/pull/98 implements is also good for removing funding of market? And if so, can you use it [here](https://github.com/gnosis/prediction-market-agent-tooling/blob/f1391b935e44284f2535dac604f2282f52c4f255/prediction_market_agent_tooling/markets/omen/omen.py#L835)?

**Comment by kongzii** [comment]
I'm learning about Github Projects and just testing what will happen if I add a new comment here now 😄

**Comment by gabrielfior** [comment]
@kongzii I suspect the logic for `redeemingPositions` (from #98 ) takes care of this, but I would like to double-check.
Do you have an example of a market where we could redeem positions from? I could then simulate the `redeemPositions` method inside a fork, and afterwards trigger the `removeFunding` method, to check if there is anything left to remove.

**Comment by kongzii** [comment]
@gabrielfior 

> I suspect the logic for redeemingPositions (from https://github.com/gnosis/prediction-market-agent-tooling/pull/98 ) DOES NOT take care of this, but I would like to double-check.

Well I don't know. That is part of this task to find out 😄  But my 90% confident guess would be that it doesn't.

> Do you have an example of a market where we could redeem positions from? 

You can create a new market using https://github.com/gnosis/prediction-market-agent-tooling/blob/f84ce2b4a35847e66cc2fa5644a06770069dc617/prediction_market_agent_tooling/markets/omen/omen.py#L362 with some reasonable `initial_funds`, for example 1 xDai and then test it out on that market.

**Comment by gabrielfior** [comment]
@kongzii The logic for withdrawing funds has been implemented. Now the question is: when should that be triggered?
My suggestion would be to have a new agent (similar to `DeployableReplicateToOmenAgent`), whose sole purpose is to scan markets and remove funds (if the markets are resolved).
My questions:
- Would you agree with such a setting?
- If yes, it would great if you could explain me how the agent `replicate-markets-to-omen` (https://console.cloud.google.com/functions/details/europe-west2/replicate-markets-to-omen?env=gen2&hl=en&project=gnosis-ai&tab=source) is normally deployed.

**Comment by kongzii** [comment]
> My suggestion would be to have a new agent 

This would mean we have multiple agents with the same private key.

`DeployableReplicateToOmenAgent` is now doing multiple steps anyway, so I'd just add it there.

However, I still have PRs waiting for review and the replicator agent is currently pointed to commit in one of them, so it can not be updated from another PR. 

So after you finish this PR, I'll add it to `DeployableReplicateToOmenAgent` that's fine, thanks!

**Comment by kongzii** [comment]
(actual usage of this is issued in https://github.com/gnosis/prediction-market-agent-tooling/issues/112)
