### ISSUE TITLE
Save logs from agents to GCP or somewhere (something S3-like would be nice)

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#91]

**Comment by gabrielfior** [comment]
In previous projects, I had a positive experience using [Sentry](https://sentry.io/for/python/). A combination I find interesting would be Loguru + Sentry, described here https://docs.sentry.io/platforms/python/integrations/loguru/.

![image](https://github.com/gnosis/prediction-market-agent-tooling/assets/4126235/9da09c27-86d4-4032-866e-7139f1c4e291)

But no hard opinions here, happy to go with any easy-to-configure solutions!

**Comment by gabrielfior** [comment]
Following guidance from the DevOps team, suggestion for implementation is simply to add Loguru (https://github.com/Delgan/loguru) globally to the project, allowing for better formating (instead of print statements).

**Comment by kongzii** [comment]
Closing as loguru was added and otherwise just GCP it is
