### ISSUE TITLE
Debug resolved Omen market probabilities in monitoring code (`get_open_and_resolved_markets`)

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#96]
Something's not right with resolved Omen markets - most have [0, 0] outcome tokens, so p_yes resolves to 0.5. Looks like they are missing `outcomeTokenMarginalPrices` values, so not sure how else to determine closed market p_yes

**Comment by kongzii** [comment]
Will be fixed by https://github.com/gnosis/prediction-market-agent-tooling/pull/201/files
